export const projectConstantsLocal = {
  LEAD_STATUS: [
    { id: 0, name: 'all', displayName: 'All Leads' },
    { id: 1, name: 'new', displayName: 'New Leads' },
    { id: 2, name: 'archived', displayName: 'Archived Leads' },
    { id: 16, name: 'followps', displayName: 'Follow Ups' },
  ],
  FILE_STATUS: [
    { id: 0, name: 'all', displayName: 'All Files' },
    { id: 3, name: 'files', displayName: 'New Files' },
    { id: 4, name: 'cni', displayName: 'CNI Files' },
  ],
  LOGIN_STATUS: [
    { id: 0, name: 'all', displayName: 'All Logins' },
    { id: 11, name: 'readyToLogin', displayName: 'Ready To Login' },
    { id: 12, name: 'filesInProcess', displayName: 'All Processed Files' },
  ],
  REJECTED_STATUS: [
    // { id: 0, name: 'all', displayName: 'All Rejects' },
    { id: 10, name: 'inHouseRejects', displayName: 'In House Rejects' },
    { id: 14, name: 'bankersRejects', displayName: 'Bankers Rejects' },
    { id: 15, name: 'cnis', displayName: 'CNIs' },
  ],
  BANKSSAVED_STATUS: [
    { id: 0, name: 'statusNotUpdated', displayName: 'Status Not Updated' },
    { id: 1, name: 'loginPending', displayName: 'Login Pending' },
    { id: 2, name: 'loginDone', displayName: 'Login Done' },
    { id: 3, name: 'camPending', displayName: 'CAM Pending' },
    { id: 4, name: 'pdPending', displayName: 'PD Pending ' },
    { id: 5, name: 'pdDone', displayName: 'PD Done' },
    { id: 6, name: 'recommending', displayName: 'Recommending' },
    { id: 7, name: 'approved', displayName: 'Approved' },
    { id: 8, name: 'rejected', displayName: 'Rejected' },
    { id: 9, name: 'hold', displayName: 'Hold' },
  ],
  APPROVALS_STATUS: [
    { id: 0, name: 'statusNotUpdated', displayName: 'Status Not Updated' },
    { id: 1, name: 'disbursed', displayName: 'Disbursed' },
    { id: 2, name: 'cnis', displayName: 'CNI' },
    { id: 3, name: 'hold', displayName: 'Hold' },
    { id: 4, name: 'agreement Done', displayName: 'Agreement Done' },
  ],
  PROCESS_CODES: [
    { id: 0, name: 'STARPOWERZ', displayName: 'STARPOWERZ' },
    { id: 1, name: 'FINBUD', displayName: 'FINBUD' },
    { id: 2, name: 'RULOANS', displayName: 'RULOANS' },
    { id: 3, name: 'ANDROMEDA', displayName: 'ANDROMEDA' },
  ],

  PRODUCT_TYPES: [
    { id: 1, name: 'UBL', displayName: 'UBL' },
    { id: 2, name: 'DOD', displayName: 'DOD' },
  ],
  CALLBACK_STATUS: [
    { id: 0, name: 'all', displayName: 'All Callbacks' },
    { id: 1, name: 'new', displayName: 'New Callbacks' },
    { id: 2, name: 'archived', displayName: 'Archived Callbacks' },
    { id: 3, name: 'converted', displayName: 'Converted Callbacks' },
  ],
  // CALLBACK_STATUS: [
  //   { id: 0, name: 'all', displayName: 'All Callbacks' },
  //   { id: 1, name: 'new', displayName: 'New Callbacks' },
  //   { id: 2, name: 'archived', displayName: 'Archived Callbacks' },
  // ],

  CALLBACK_STATUS_REPORTS: [
    { id: 1, name: 'new', displayName: 'New Callbacks' },
    { id: 2, name: 'archived', displayName: 'Archived Callbacks' },
  ],
  LENDERS_STATUS: [
    { id: 0, name: 'all', displayName: 'All Lenders' },
    { id: 1, name: 'new', displayName: 'New Lenders' },
    { id: 2, name: 'archived', displayName: 'Archived Lenders' },
  ],
  USER_STATUS: [
    { id: 0, name: 'all', displayName: 'All Users' },
    { id: 1, name: 'Active', displayName: 'Active Users' },
    { id: 2, name: 'Inactive', displayName: 'Inactive Users' },
  ],

  EMPLOYMENT_STATUS: [
    { id: 1, name: 'employed', displayName: 'Employed' },
    { id: 2, name: 'self-employed', displayName: 'Self Employed' },
  ],

  USER_TYPE: [
    { id: 1, name: 'Super Admin', displayName: 'Super Admin' },
    { id: 2, name: 'Admin', displayName: 'Admin ' },
    { id: 3, name: 'Tele Sales', displayName: 'Tele Sales' },
    { id: 4, name: 'Operational Team', displayName: 'Operational Team' },
    { id: 5, name: 'HR Admin', displayName: 'HR Admin' },
  ],
  BANK_DOCUMENTS_STATUS: [
    { id: 0, name: 'all', displayName: 'All Documents' },
    { id: 1, name: 'new', displayName: 'New Documents' },
    { id: 2, name: 'archived', displayName: 'Archived Documents' },
  ],
  BANKERS_STATUS: [
    { id: 0, name: 'all', displayName: 'All Lenders' },
    { id: 1, name: 'new', displayName: 'New Lenders' },
    { id: 2, name: 'archived', displayName: 'Archived Lenders' },
  ],

  LOAN_TYPES: [
    { id: 1, name: 'businessLoan', displayName: 'Business Loan' },
    { id: 2, name: 'personalLoan', displayName: 'Personal Loan' },
    { id: 3, name: 'homeLoan', displayName: 'Home Loan' },
    { id: 4, name: 'lap', displayName: 'LAP' },
    { id: 5, name: 'professionalLoans', displayName: 'Professional Loan' },
    { id: 5, name: 'carLoan', displayName: 'car Loan' }
  ],
  LEAD_INTERNAL_STATUS: [
    { id: '1', status: 'new', displayName: 'New' },
    { id: '2', status: 'archived', displayName: 'Archived' },
    { id: '3', status: 'files', displayName: 'Files' },
    { id: '4', status: 'cni', displayName: 'CNI' },
    { id: '5', status: 'creditEvaluation', displayName: 'Credit Evaluation' },
    { id: '6', status: 'login', displayName: 'Login' },
    { id: '7', status: 'approval', displayName: 'Approval' },
    { id: '8', status: 'disbursal', displayName: 'Disbursal' },
    { id: '9', status: 'rejected', displayName: 'Rejected' },
    { id: '10', status: 'inHouseRejects', displayName: 'In House Rejects' },
    { id: '11', status: 'readyForLogin', displayName: 'Ready For Login' },
    { id: '12', status: 'filesInProcess', displayName: 'Files In Process' },
    // { id: '13', status: 'partialFiles', displayName: 'Partial Files' },
    { id: '14', status: 'bankerRejects', displayName: 'Banker Rejects' },
    { id: '15', status: 'cni', displayName: 'CNI' },
    { id: '16', status: 'followups', displayName: 'Follow Ups' },
  ],

  CALLBACK_INTERNAL_STATUS: [
    { id: '1', status: 'new', displayName: 'New' },
    { id: '2', status: 'archived', displayName: 'Archived' },
    { id: '3', status: 'converted', displayName: 'Converted' },
  ],
  LEAD_INTERNAL_STATUS_REPORTS: [
    { id: '1', status: 'new', displayName: 'New Leads' },
    { id: '2', status: 'archived', displayName: 'Archived Leads' },
    { id: '16', status: 'followups', displayName: 'Follow Ups' },
    { id: '3', status: 'files', displayName: 'Files' },
    // { id: '4', status: 'partialFiles', displayName: 'Partial Files' },
    { id: '5', status: 'creditEvaluation', displayName: 'Credit Evaluation' },
    { id: '11', status: 'readyForLogin', displayName: 'Ready For Login' },
    { id: '10', status: 'inHouseRejects', displayName: 'In House Rejects' },
  ],

  TIMELINE_STATUS: [
    { index: 1, name: 'Draft', displayName: 'Draft' },
    { index: 2, name: 'ApprovalRequired', displayName: 'Approval Required' },
    { index: 3, name: 'CreditApproved', displayName: 'Credit Verified' },
    { index: 4, name: 'SchemeConfirmed', displayName: 'Scheme Confirmed' },
    { index: 5, name: 'BranchApproved', displayName: 'BM Approved' },
    { index: 6, name: 'ConsumerAccepted', displayName: 'Consumer Accepted' },
    { index: 7, name: 'Sanctioned', displayName: 'Sanctioned' },
    { index: 8, name: 'OperationsVerified', displayName: 'Operations Verify' },
  ],
  BUSINESS_ENTITIES: [
    { displayName: 'Proprietorship', name: 'proprietorship' },
    { displayName: 'Partnership', name: 'partnership' },
    { displayName: "LLP", name: "llp" },
    { displayName: 'Private Limited', name: 'privateLimited' },
  ],
  // STATE_ENTITIES: [
  //   { displayName: 'Andhra Pradesh', name: 'andhra pradesh' },
  //   { displayName: 'Telangana', name: 'telangana' },
  // ],
  STATE_ENTITIES: [
    // States
    { displayName: 'Andhra Pradesh', name: 'andhra pradesh' },
    { displayName: 'Arunachal Pradesh', name: 'arunachal pradesh' },
    { displayName: 'Assam', name: 'assam' },
    { displayName: 'Bihar', name: 'bihar' },
    { displayName: 'Chhattisgarh', name: 'chhattisgarh' },
    { displayName: 'Goa', name: 'goa' },
    { displayName: 'Gujarat', name: 'gujarat' },
    { displayName: 'Haryana', name: 'haryana' },
    { displayName: 'Himachal Pradesh', name: 'himachal pradesh' },
    { displayName: 'Jharkhand', name: 'jharkhand' },
    { displayName: 'Karnataka', name: 'karnataka' },
    { displayName: 'Kerala', name: 'kerala' },
    { displayName: 'Madhya Pradesh', name: 'madhya pradesh' },
    { displayName: 'Maharashtra', name: 'maharashtra' },
    { displayName: 'Manipur', name: 'manipur' },
    { displayName: 'Meghalaya', name: 'meghalaya' },
    { displayName: 'Mizoram', name: 'mizoram' },
    { displayName: 'Nagaland', name: 'nagaland' },
    { displayName: 'Odisha', name: 'odisha' },
    { displayName: 'Punjab', name: 'punjab' },
    { displayName: 'Rajasthan', name: 'rajasthan' },
    { displayName: 'Sikkim', name: 'sikkim' },
    { displayName: 'Tamil Nadu', name: 'tamil nadu' },
    { displayName: 'Telangana', name: 'telangana' },
    { displayName: 'Tripura', name: 'tripura' },
    { displayName: 'Uttar Pradesh', name: 'uttar pradesh' },
    { displayName: 'Uttarakhand', name: 'uttarakhand' },
    { displayName: 'West Bengal', name: 'west bengal' },

    // Union Territories
    { displayName: 'Andaman and Nicobar Islands', name: 'andaman and nicobar islands' },
    { displayName: 'Chandigarh', name: 'chandigarh' },
    { displayName: 'Dadra and Nagar Haveli and Daman and Diu', name: 'dadra and nagar haveli and daman and diu' },
    { displayName: 'Delhi', name: 'delhi' },
    { displayName: 'Jammu and Kashmir', name: 'jammu and kashmir' },
    { displayName: 'Ladakh', name: 'ladakh' },
    { displayName: 'Lakshadweep', name: 'lakshadweep' },
    { displayName: 'Puducherry', name: 'puducherry' }
  ],
  BUSINESS_TURNOVER: [
    { displayName: 'Upto 1 Crore', name: 'upto 1 crore' },
    { displayName: '1 - 3 Crores', name: '1 - 3 crores' },
    { displayName: '3 - 5 Crores', name: '3 - 5 crores' },
    { displayName: '5 - 10 Crores', name: '5 - 10 crores' },
    { displayName: 'Above 10 Crores', name: 'above 10 crores' },
  ],
  // YES_OR_NO: [
  //   { displayName: 'Yes', name: 'yes' },
  //   { displayName: 'No', name: 'no' },
  // ],

  YES_OR_NO: [
    { displayName: 'Own', name: 'own' },
    { displayName: 'Rented', name: 'rented' },
  ],
  NATURE_OF_BUSINESS: [
    { displayName: 'Manufacturing', name: 'manufacturing' },
    { displayName: 'Trading - Distribution', name: 'trading - distribution' },
    { displayName: 'Trading - Wholesaler', name: 'trading - wholesaler' },
    { displayName: 'Trading - Retail', name: 'trading - retail' },
    { displayName: 'Service Provider', name: 'service provider' },
    { displayName: 'Constructions', name: 'constructions' },
  ],
  FILE_REMARKS: [
    { id: 1, status: 'will_share_documents', displayName: 'Will Share Documents' },
    { id: 2, status: 'received_partials', displayName: 'Received Partials' },
    { id: 3, status: 'roi_concern', displayName: 'Loan Amount Concern' },
    { id: 4, status: 'client_not_responding', displayName: 'Client Not Responding to Calls' },
    { id: 5, status: 'client_out_of_station', displayName: 'Client Out of Station' },
    { id: 6, status: 'not_interested_presently', displayName: 'Present Not Interested' },
    { id: 7, status: 'low_vintage', displayName: 'Low Vintage' },
    { id: 8, status: 'multiple_banks_not_interested', displayName: 'Multiple Banks Not Interested' },
    { id: 9, status: 'cibil_bad', displayName: 'Cibil Bad' },
    { id: 10, status: 'roi_concern', displayName: 'ROI Concern' },
    { id: 11, status: 'tenure_concern', displayName: 'Tenure Concern' }
  ],
  LEAD_REMARKS: [
    { id: 1, status: 'client_will_share_documents', displayName: 'Will share documents' },
    { id: 2, status: 'client_asked_office_visit', displayName: 'Office visit requested' },
    { id: 3, status: 'needs_discussion_with_partners', displayName: 'Discuss with partners' },
    { id: 4, status: 'client_not_responding', displayName: 'Not responding' },
    { id: 5, status: 'client_out_of_station', displayName: 'Out of station' },
    { id: 6, status: 'needs_approx_roi_details', displayName: 'Approx ROI details' },
    { id: 7, status: 'needs_project_confirmation', displayName: 'Project confirmation' },
    { id: 8, status: 'client_trying_other_banks', displayName: 'Trying other banks' },
    { id: 9, status: 'multiple_bank_confirmations', displayName: 'Multiple bank confirmation' }
  ],
  SALARYED_OR_UNSALARYED: [
    { id: 1, status: 'Salaried', displayName: 'Salaried' },
    { id: 2, status: 'selfEmployed', displayName: 'Self Employed' }
  ],
  DOCTOR_OR_CA: [
    { id: 1, status: 'doctor', displayName: 'Doctor' },
    { id: 2, status: 'ca', displayName: 'CA' }
  ],
  CAR_TYPE: [
    { id: 1, status: 'used', displayName: 'Used Car' },
    { id: 2, status: 'new', displayName: 'New Car' }
  ],

  CORPORATE_DSA: [
    { id: 1, name: "BALAJI FINCORP", statusName: "Active" },
    { id: 2, name: "FA WIZARD PVT LTD", statusName: "Active" },
    { id: 3, name: "FINBUD FINANCIAL SERVICES PVT LTD", statusName: "Active" },
    { id: 4, name: "FINEOTERIC CONSULTING PVT LTD", statusName: "Active" },
    { id: 5, name: "FINFREE ENTERPRISES", statusName: "Active" },
    { id: 6, name: "FUNDING MILLIONS", statusName: "Active" },
    { id: 7, name: "OSM CAPITAL ADVISORS PVT LTD", statusName: "Active" },
    { id: 8, name: "BRIGHTWORTH ADVISORS PVT LTD", statusName: "Active" },
    { id: 9, name: "EKAGRA FINSERV PVT LTD", statusName: "Active" },
    { id: 10, name: "EXCEL INCORPORATION", statusName: "Active" },
    { id: 11, name: "FINNEST TAHERA FINANCIAL SERVICES PVT LTD", statusName: "Active" },
    { id: 12, name: "FINSPARKK MANAGEMENT CONSULTANT PVT LTD", statusName: "Active" },
    { id: 13, name: "JENYUFIN SOLUTIONS PVT LTD", statusName: "Active" },
    { id: 14, name: "MINOLA DIXIT", statusName: "Active" },
    { id: 15, name: "MOLLI SHANKER", statusName: "Active" },
    { id: 16, name: "MS SRINIDHI FINSOL", statusName: "Active" },
    { id: 17, name: "MY MUDRA FINCROP PVT LTD", statusName: "Active" },
    { id: 18, name: "NAMAN FINANCIAL SOLUTIONS", statusName: "Active" },
    { id: 19, name: "PRIYANKAYADAV", statusName: "Active" },
    { id: 20, name: "RAHUL CREDIT SERVICES LLP", statusName: "Active" },
    { id: 21, name: "IMPETUS ADCON PVT LTD", statusName: "Active" },
    { id: 22, name: "TRUE ASQUARE FINOVATION PVT LTD", statusName: "Active" },
    { id: 23, name: "ARK SOLUTIONS", statusName: "Active" },
    { id: 24, name: "SEHAJ MANAGEMENT CONSULTANTS PVT LTD", statusName: "Active" },
    { id: 25, name: "SHRADDHA CORPORATION", statusName: "Active" },
    { id: 26, name: "S K MARKETING", statusName: "Active" },
    { id: 27, name: "SANSOW INC", statusName: "Active" },
    { id: 28, name: "MANJU DONKADA", statusName: "Active" },
    { id: 29, name: "SANTHOSH MARKETING", statusName: "Active" },
    { id: 30, name: "SHANI FINSERVE PVT LTD", statusName: "Active" },
    { id: 31, name: "NARASIMHAREDDY THALAKANTI", statusName: "Active" },
    { id: 32, name: "MONEY MATTERS CO", statusName: "Active" },
    { id: 33, name: "TRIANGULAR INTERMEDIARIES SERVICES", statusName: "Active" },
    { id: 34, name: "SANDHYA TIWARI", statusName: "Active" },
    { id: 35, name: "IFLS FINANCIAL SERVICES", statusName: "Active" },
    { id: 36, name: "VERTEXT FINANCIAL SOLUTIONS", statusName: "Active" },
    { id: 37, name: "MEET PANKAJ BHAI PATEL", statusName: "Active" },
    { id: 38, name: "TRUEWIN FINTECH", statusName: "Active" },
    { id: 39, name: "GENERATION NEXT BPO SERVICES", statusName: "Active" },
    { id: 40, name: "SIDDHI IMAGINE FINTECH CONSULTANC PVT LTD", statusName: "Active" },
    { id: 41, name: "VELOCITY INC", statusName: "Active" },
    { id: 42, name: "SBJ FINTECH SERVICES PVT LTS", statusName: "Active" },
    { id: 43, name: "RAAJ KHOSLA AND CO PVT LTD", statusName: "Active" },
    { id: 44, name: "REALTURITY BUSINESS ADIVSORY PVT LTD", statusName: "Active" },
    { id: 45, name: "ANDROMEDASALES AND DISTRIBUTION PVT LTD", statusName: "Active" },
    { id: 46, name: "AADIFIDELIS SOLUTIONS PVT LTD", statusName: "Active" },
    { id: 47, name: "SRS CAPITAL PVT LTD", statusName: "Active" },
    { id: 48, name: "CATEYE CONSULTANCY SERVIES PVT LTD", statusName: "Active" },
    { id: 49, name: "RULOANS DISTRIBUTION SERVICES PVT LTD", statusName: "Active" },
    { id: 50, name: "APEX FINANCIAL SERVICES", statusName: "Active" },
    { id: 51, name: "BATWAL FINANCE", statusName: "Active" },
    { id: 52, name: "FINTRIANGLE SERVICES", statusName: "Active" },
    { id: 53, name: "HEXAFIN CONSULTANCY PVT LTD", statusName: "Active" },
    { id: 54, name: "V AND V CONSULTANTS", statusName: "Active" },
    { id: 55, name: "QDN MANAGEMENT PVT LTD", statusName: "Active" },
    { id: 56, name: "FINKRISH SOLUTIONS PVT LTD", statusName: "Active" },
    { id: 57, name: "ASQUARIAN CONSUTLANTS PVT LTD", statusName: "Active" },
    { id: 58, name: "CHASEFLY", statusName: "Active" },
    { id: 59, name: "SHRI BALAJI FINANCIALS", statusName: "Active" },
    { id: 60, name: "PS GRACE MONEY SOLUTIONS PVT LTD", statusName: "Active" },
    { id: 61, name: "JP MANI INDIA PVT LTD", statusName: "Active" },
    { id: 62, name: "FINWIZZ FINANCIAL SERVICES PVT LTD", statusName: "Active" },
    { id: 63, name: "AADI TRADEMENT PVT LTD", statusName: "Active" },
    { id: 64, name: "ANURADHA SINGH", statusName: "Active" },
    { id: 65, name: "ARAHEHA CONSULTANT PVT LTD", statusName: "Active" },
    { id: 66, name: "START POWERZ DIGITAL TECHNOLOGIES PVT LTD", statusName: "Active" },
  ],

  // RAZORPAY_KEY_ID: "rzp_test_OryiPavGPST3CU",
  BASE_URL: 'http://localhost:5002/',
  // BASE_URL: 'https://rest.thefintalk.in:5002/',
  RAZORPAY_KEY_ID: "rzp_live_ZC5B0vsPZ7UxUs",
  VERSION_DESKTOP: '0.0.0',
};
